config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|pt/ do
    resources :rooms do
      resources :reviews, only: [:create, :update], module: :rooms
    end
    resources :users
  end
  get '/:locale' => 'home#index', locale: /en|pt/

  resource :confirmation, only: [:show]

  resource :user_sessions, only: [:create, :new, :destroy]
  
  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

	has_many :reviews, dependent: :destroy
	has_many :rooms, dependent: :destroy

	scope :confirmed, -> {where.not(confirmed_at: nil)} # restringe o escopo aos usuários que já confirmaram o email de validação

	validates_presence_of :email, :full_name, :location
	#validates_confirmation_of :password
	validates_length_of :bio, minimum: 30, allow_blank: false
	validates_uniqueness_of :email
	
	has_secure_password
	
	validate :email_format

	before_create do |user|
		user.confirmation_token = SecureRandom.urlsafe_base64
	end

	def self.authenticate(email,password)
		confirmed.find_by(email: email).try(:authenticate,password)
		#user = confirmed.find_by(email: email)
		#if user.present?
		#	user.authenticate(password)
		#end
	end

	def confirm!
		return if confirmed?

		self.confirmed_at = Time.current
		self.confirmation_token = ''
		save!
	end

	def confirmed?
		confirmed_at.present?
	end
	
	private
	#Essa validação pode ser representada da seguinte forma:
	#validates_format_of :email,with: EMAIL_REGEXP
	def email_format
		errors.add(:email, :invalid) unless email.match(EMAIL_REGEXP)
	end
end

app/controllers/users_controller.rb
class UsersController <ApplicationController
	before_action :require_no_authentication, only: [:new,:create]
	before_action :can_change, only: [:edit,:update]
	def show
		@user = User.find(params[:id])
	end
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		if @user.save
			Signup.confirm_email(@user).deliver
			
			redirect_to @user,
				notice: 'Cadastro realizado com sucesso!'
		else
			render action: :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to @user,
				notice: 'Cadastro atualizado com sucesso!'
		else
			render action: :edit
		end
	end
	private
	def user_params
		params.require(:user).permit(:email,:full_name,:location,:password,:password_confirmation, :bio)
	end

	def can_change
		unless user_signed_in? && current_user == user
			redirect_to user_path(params[:id])
		end
	end

	def user
		@user ||= User.find(params[:id])
	end
end

app/views/users/_form.html.erb
 <% if @user.errors.any? %>
	<div id="error_explanation">
		<%= t 'general.form_error' %>
	</div> 
<% end %> 
<%= form_for @user do |f| %>
	<p>
		<%= f.label :full_name %><br>
		<%= f.text_field :full_name %>
		<%= error_tag @user, :full_name %>
		<!--<% if @user.errors.has_key? :full_name %>
			<div class="error_message">
				<%= @user.errors[:full_name].first %>
			</div>
		<% end %> -->
	</p>
	<p>
		<%=  f.label :location %><br>
		<%= f.text_field :location %>
		<%= error_tag @user, :location %>
	</p>
	<p>
		<%= f.label :email %><br>
		<%= f.text_field :email %>
		<%= error_tag @user, :email %>
	</p>
	<p>
		<%= f.label :password %><br>
		<%= f.password_field :password %>
		<%= error_tag @user, :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %><br>
		<%= f.password_field :password_confirmation %>
		<%= error_tag @user, :password_confirmation %>
	</p>
	<p>
		<%= f.label :bio %><br>
		<%= f.text_area :bio %>
		<%= error_tag @user, :bio %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/users/edit.html.erb
<h1><%= t'.title' %></h1>

<%= render 'form' %>

<%= link_to t('links.back'), @user %>

app/views/users/new.html.erb
<h1><%= t '.title' %></h1><!--pode ser user.new.title,mas o contexto já é inserido -->

<%= render 'form' %>

<%= link_to t('links.back'), root_path %>

app/views/users/show.html.erb
<h1><%= t'.title', user_name: @user.full_name %></h1>

<ul>
	<li><%= t '.location',location:@user.location %></li>
	<li><%= t '.bio', bio: @user.bio %></li>
</ul>

<%= link_to t('.edit'), edit_user_path(@user) %>
<%= link_to 'Home', root_path %>