config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|pt/ do
    resources :rooms do
      resources :reviews, only: [:create, :update], module: :rooms
    end
    resources :users
  end
  get '/:locale' => 'home#index', locale: /en|pt/

  resource :confirmation, only: [:show]

  resource :user_sessions, only: [:create, :new, :destroy]
  
  root 'home#index'

end

app/models/room.rb
class Room < ActiveRecord::Base
	extend FriendlyId

	belongs_to :user
	has_many :reviews, dependent: :destroy

	has_many :reviewed_rooms, through: :reviews, source: :room
	
	validates_presence_of :title, :location, :description
	validates_presence_of :slug
	validates_length_of :description, minimum: 30, allow_blank: false

	mount_uploader :picture, PictureUploader
	friendly_id :title, use: [:slugged, :history]

	
	 def self.most_recent
    	order(created_at: :desc)
	 end


	def complete_name
		"#{title}, #{location}"
	end

	def self.search(query)
		if query.present?
			where(['location LIKE :query OR title LIKE :query OR description LIKE :query',query: "%#{query}%"])
		else
			all
		end
	end

end

app/controllers/rooms/reviews_controllers.rb
class Rooms::ReviewsController < ApplicationController
	before_filter :require_authentication

	def create
		review = room.reviews.
		find_or_initialize_by(user_id: current_user.id)
		
		review.update!(review_params)

		head :ok
	end

	def update
		create
	end

	private

	def room 
		@room ||= Room.find(params[:room_id])
	end

	def review_params
		params.require(:review).permit(:points)
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  PER_PAGE = 10

  before_action :set_room, only: [:show]
  before_action :set_users_room, only: [:edit, :update, :destroy]
  before_action :require_authentication,
    only: [:new, :edit, :create, :update, :destroy]


  def index
   #O método #map, de coleções, retornará um novo Array
   #contendo o resultado do bloco. Dessa forma, para cada
   #quarto, retornaremos o presenter equivalente
   #@rooms = Room.most_recent.map do |room|
      #Nao exibiremos o formulário na listagem
    #  RoomPresenter.new(room,self,false)

    @search_query = params[:q]
    rooms = Room.search(@search_query).
    most_recent.page(params[:page]).per(PER_PAGE)

    @rooms = RoomCollectionPresenter.new(rooms,self)
  end


  def show
    if user_signed_in?
      @user_review = @room.reviews.
      find_or_initialize_by(user_id: current_user.id)
    end
  end

  def new
    @room = current_user.rooms.build
  end

  def edit
  end

  def create
    @room = current_user.rooms.build(room_params)
      if @room.save
        redirect_to @room, notice: t('flash.notice.room_created')
      else
        render :new
      end
  end

 
  def update
      if @room.update(room_params)
        redirect_to @room, notice: t('flash.notice.room_updated')
      else
        render :edit
      end
  end

  def destroy
    @room.destroy
    redirect_to rooms_url
  end

  private

    def set_room
      room_model = Room.friendly.find(params[:id])
      @room = RoomPresenter.new(room_model, self)
    end

    def set_users_room
      @room = current_user.rooms.friendly.find(params[:id])
    end


    def room_params
      params.require(:room).permit(:title, :location, :description, :picture)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
	def belongs_to_user(room)
		user_signed_in? && room.user == current_user
	end
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2>O formulário contém erros:</h2>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <% if @room.errors.has_key? :title %> <!-- UMA MANEIRA DE EXIBIR ERROS-->
    <div class="error_message">
      <%= @room.errors[:title].first %>
    </div>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
    <%= error_tag @room, :location %> <!-- OUTRA MANEIRA DE EXIBIR ERROS COM OS HELPERS-->
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
    <%= error_tag @room, :description %>
  </div>
  <div>
    <%= f.label :picture %>
    <%= f.file_field :picture %>
    <%= error_tag @room, :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/_review.html.erb
<section class="review">
	<% if room.show_form? %>
		<%= render partial: 'review_form', locals: {room: room} %>
	<% else %>
		<% room.stars.times do %>
			<%= fa_icon 'star' %>
		<% end %>
		<% (room.review_points.max - room.stars).times do %>
			<%= fa_icon 'empty-star' %>
		<% end %>
		<%= t '.stats', count: room.total_reviews %>
	<% end %>
</section>

app/views/rooms/_review_form.html.erb
<% if room.can_review? %>
	<%= form_for room.review_route, remote: true do |f| %>
		<% room.review_points.each do |point| %>
			<%= f.radio_button :points, point %>
			<%= f.label :points, value: point do %>
				<%= fa_icon 'star' %>
			<% end %>
		<% end %>
		<%= f.submit %>
	<% end %>
<% else %>
	<span class="login_required">
		<%= t('.login_to_review') %>
	</span>
<% end %>

app/views/rooms/_room.html.erb
  <article class="room">
    <h2><%= link_to highlight(room.title, @search_query), room.route %></h2>

    <%= render partial: 'review', locals: {room: room} %>

    <span class="created">
      <%= t'.owner_html', owner: room.user.full_name, when: l(room.created_at, format: :short) %>
    </span>
    <p>
      <span class="location">
        <%= link_to highlight(room.location, @search_query), "https://maps.google.com/?q=#{room.location}", target: :blank %>
      </span>
    </p>
    <div class="room-description">
    <%= link_to(
          image_tag(room.thumb_url),
          room.picture_url
        ) if room.has_picture? %>
    <p><%= highlight(room.description || '', @search_query) %></p>
    </div>
    <% if belongs_to_user(room) %>
      <ul>
        <li><%= link_to t('.edit'), edit_room_path(room.route) %></li>
        <li><%= link_to t('.destroy'), room_path(room.route),method: :delete, data: {confirm: t('dialogs.destroy')} %></li>
        </ul>
    <% end %>
  </article>

app/views/rooms/_search.html.erb
<%= form_tag rooms_path, method: :get, class: 'search' do %>
	<% text_field_tag :q, @search_query, placecholder: t('.search_for') %>
<% end %>

app/views/rooms/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<%= render 'search' %>

<h1>
	<% if @search_query.present? %>
		<%= t '.search_results' %>
	<% else %>
		<%= t '.title' %>
	<% end %>
</h1>

<%= render @rooms %>

<%= paginate @rooms %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<!--<p>
  <strong>Title:</strong>
  <%= @room.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @room.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>
-->
<%= render @room %>