config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|pt/ do
    resources :rooms do
      resources :reviews, only: [:create, :update], module: :rooms
    end
    resources :users
  end
  get '/:locale' => 'home#index', locale: /en|pt/

  resource :confirmation, only: [:show]

  resource :user_sessions, only: [:create, :new, :destroy]
  
  root 'home#index'

end

app/views/layouts/_user_navbar.html.erb
<nav>
	<ul>
		<li><%= link_to t('layout.new_room'),new_room_path %></li>
		<li><%= link_to t('layout.rooms'),rooms_path %> </li>
		<li><%= link_to t('layout.my_profile'),user_path(current_user) %></li>
		<li>
			<%= link_to t('layout.signout'), user_sessions_path, method: :delete %>
		</li>
	</ul>
</nav>

app/views/layouts/_visitor_navbar.html.erb
<nav>
	<ul>
		<li><%= link_to t('layout.rooms'), rooms_path %></li>
		<li><%= link_to t('layout.signup'), new_user_path %></li>
		<li><%= link_to t('layout.signin'), new_user_sessions_path %></li>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Colchonet</title>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Pacifico">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<div id="herder-wrap">
		<h1><%= link_to "colcho.net", root_path %></h1>
		<% if user_signed_in? %>
			<%= render 'layouts/user_navbar' %>
		<% else %>
			<%= render 'layouts/visitor_navbar' %>
		<% end %>
	</div>
</header>
<div id="content">
	<% if notice.present? %>
		<p id="notice"><%= notice %> </p>
	<% end %>
	<% if alert.present? %>
		<p id="alert"><%= alert %></p>
	<% end %>
</div>
<%= yield %>

</body>
</html>